### ISSUE TITLE
deprecation compatibility.

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-device-orientation#43]
I know this plugin is now deprecated, but the last version of it was 2.0.1 - though it looks like someone was still doing a dev version 2.0.2.

My question is when it was deprecated, what were the version levels of cordova-ios and cordova-android (or cordova-cli) that this plugin was no longer needed?

My app is running significantly behind all the latest and greatest revs - so I need to determine that as of (example) android@6.3 and ios@4.5 this plugin is not needed.

As well, if the plugin is no longer needed, where is the documentation on how to call the new integrated functions (previously used by this plugin) for device orientation functionality?

**Comment by biji** [comment]
I always get 90 deg on start when using browser's api. Will try this plugin , see if this better

**Comment by jcesarmobile** [comment]
The release script created a new 2.0.2-dev, but no work has been done after that as it's deprecated.
